### ISSUE TITLE
Integration with glslify

### ISSUE THREAD

**Issue by Qix-** [docd27/rollup-plugin-glsl-optimize#1]
Hi there,

We're using glslify in our Rollup config, but I'd also like to integrate SPIRV optimizations as well. As of now, the `import` in our codebase will correctly invoke glslify but then I believe the contents are being replaced with the resulting string, so by the time glsl-optimize's plugin gets hit, there's no Vinyl record that is a .glsl file and thus nothing gets run through the optimizer.

What's the best way to handle the combinations of these plugins? I'm having trouble even telling if the plugin is running or doing anything (Rollup's debugging capabilities seem to be lacking here).

Any advice? Thanks so much!

**Comment by docd27** [comment]
Hi 👋

Since I guess glslify is quite a common use-case and there wasn't really any other solution to clean interoperation with [rollup-plugin-glslify](https://github.com/glslify/rollup-plugin-glslify), I went ahead and implemented basic support* for processing shader sources through glslify directly in this plugin.

If you set ``glslify: true`` and install it to your dev dependencies with ``npm i -D glslify`` you can give it a try.

Interested to hear how it goes!

\* A possible future enhancement is meaningful glslangValidator/browser error messages referencing the right file glslify files and line numbers, like you already get via #include and this plugin alone. But that's a significant undertaking considering glslify itself won't emit #line directives.

**Comment by Qix-** [comment]
I appreciate that! :) Thank you so much.

I'm having a bit of trouble getting it to work - currently I just run my code through `rollup-plugin-glslify` with no additional parameters, and then my imports are more or less `import VertexShader from './my-vert-shader.glsl'`.

However, replacing `rollup-plugin-glslify` with `rollup-plugin-glsl-optimize` followed by `rollup-plugin-glsl` (as mentioned in the docs) results in the shaders still having the `#pragma glslify` directives in there:

```javascript
	rollupGlslOptimize({
		glslify: true
	}),
	rollupGlsl({
		include: '**/*.glsl',
		exclude: '**/*.js',
		sourceMap: false
	}),
```

Results in

```javascript
// Snipped for brevity
var VERTEX = "... \n#pragma glslify: noise = require('glsl-noise/simplex/3d');\n...";
```

Any ideas on how to fix this? :)

As for the line directives I (personally) care much less about those as debugging shader syntax errors is more or less easy to deal with in this case. Just getting it to build right and optimize is the main goal :)

Thanks again, I really appreciate it!

**Comment by docd27** [comment]
That's strange - I added some tests in cab815c5bb33d545b137c487c7975ecc8821cb8e involving glsl-noise that confirm #pragma glslify is correctly processed. It's the example from the glslify readme - though I did wrap snoise3 in a vec3() due to the increased strictness of glslangValidator / GLSL ES 3.0 (but imo that's a good thing!)

You shouldn't need ``rollup-plugin-glsl`` - could you try without it? Also confirm that you're definitely on v0.0.9 :)

**Comment by docd27** [comment]
Also another potential issue in your example is that ``my-vert-shader.glsl`` will need to be ``my-vert-shader.vert.glsl`` or the other options given in the [shader stages table](https://github.com/docd27/rollup-plugin-glsl-optimize#shader-stages)

This is because the Khronos binaries need to know the shader stage (though the error should be self explanatory)

**Comment by Qix-** [comment]
Aha, okay - in the real project they were just called `vert.glsl` and `frag.glsl` - changing them to `foo.vert.glsl` etc appears to be triggering SPIRV correctly. Previously there were no errors.

> Also confirm that you're definitely on v0.0.9

Yep yep!

```console
$  cat package.json | grep glsl-opt
"rollup-plugin-glsl-optimize": "0.0.9",
```

> You shouldn't need `rollup-plugin-glsl` - could you try without it?

Yep you're right, works fine :)

---

All appears to be working now! I appreciate the help, this is great! Thank you so much :)
